### ISSUE TITLE
Detect when a post or comment was removed by Reddit instead of by a sub's mods and show those posts differently

### ISSUE THREAD

**Issue by TiagoTiago** [snew/snew#8] opened 2018-03-04 22:59 UTC
Sometimes things get deleted by Reddit itself, without any input from a sub's mods; it would be good to add a mention of that in the logs, and show that information when opening a thread or comment page.

**Comment by go1dfish** [comment] 2018-03-14 14:48
Closing this as a duplicate of https://github.com/snew/snew/issues/7

Because that would include who removed it, and afaik public mod logs would be the only way I could tell who removed a piece of content.

**Closed as completed by go1dfish** 2018-03-14 14:48 UTC
